### ISSUE TITLE
Créer un utilisateur

### ISSUE THREAD

**Issue by brandonsueur** [gestionpompier/api#1]
## 🗃 Ce que contiens la table `users`

- uuid
- first_name
- last_name
- email
- role
- matricule
- birthday
- rank
  - sapeur deuxième classe
  - sapeurs première classe
  - caporal 
  - caporal chef 
  - sergent 
  - sergent-chef 
  - adjudant
  - adjudant-chef
  - lieutenant
  - capitaine
- password
- is_active
- created_at
- updated_at

## 🤝 Les champs obligatoire pour créer un utilisateur

- first_name
- last_name
- email
- matricule
- password

**Comment by Drazozo** [comment]
Hello, 
J'ai ajouté quelques champs ;)
